// Generated by CoffeeScript 1.4.0
(function() {
  var attrEscape, pixelValue;

  attrEscape = function(attr) {
    return attr.replace(/"/g, '%22').replace(/'/g, '%27');
  };

  pixelValue = function(value) {
    return "" + value + "px";
  };

  this.generateHoverImages = function() {
    $('.hover-image').remove();
    return $('img.hover-zoom').each(function(i) {
      var $this, hoverImageId, largeImgSrc;
      $this = $(this);
      largeImgSrc = $this.data('img-large');
      if (largeImgSrc == null) {
        return;
      }
      hoverImageId = "hover-image-" + i;
      $('body').append("<div id='" + hoverImageId + "' class='hover-image'>\n  <img src='" + (attrEscape(largeImgSrc)) + "' />\n</div>");
      return $this.data('hover-image-el', $("#" + hoverImageId));
    }).mousemove(function(e) {
      var $hoverImage, clientX, clientY, imageHeight, left, mouseOffset, right, windowHeight, windowWidth;
      $hoverImage = $(this).data('hover-image-el');
      clientX = e.clientX, clientY = e.clientY;
      windowHeight = innerHeight;
      windowWidth = innerWidth;
      imageHeight = $hoverImage.outerHeight();
      mouseOffset = 25;
      if ((clientY + imageHeight) > windowHeight) {
        clientY = Math.round((windowHeight - imageHeight) / 2);
      }
      if (clientX > (windowWidth / 2)) {
        right = pixelValue(windowWidth - clientX + mouseOffset);
        left = '';
      } else {
        left = pixelValue(clientX + mouseOffset);
        right = '';
      }
      return $hoverImage.css({
        display: 'block',
        left: left,
        right: right,
        top: pixelValue(clientY)
      });
    }).mouseleave(function() {
      return $(this).data('hover-image-el').css('display', 'none');
    });
  };

  $(function() {
    return generateHoverImages();
  });

}).call(this);
